### PR TITLE
Play 2.7.x

### PR DESCRIPTION
**Pull request by AmazingDreams**
These are the changes I needed to do to get it working for play 2.7.x via publishLocal.

### CODE REVIEW

**Comment by mkurz** [comment]
@AmazingDreams I think you can also add Scala `2.13.0-M5` to every `crossScalaVersions` setting.

**Comment by lglossman** [comment]
@AmazingDreams @mkurz Is there a expected release date for this? I tested this PR and seems to be working as expected.

**Comment by mkurz** [comment]
Depends if and when @schaloner finds time to review/merge this pull request and cut the release. He is very busy these days.

**Comment by schaloner** [comment]
It took forever, so my deepest apologies to @mkurz after all his hard work, but 2.7.0 has just been released.

**Comment by mkurz** [comment]
@schaloner Thanks! However you just commented into the `deadbolt-2-SCALA`  repo :wink: However you talk about `deadbolt-2-JAVA`...
Anyway, thank you very much!

**Comment by schaloner** [comment]
@mkurz brainfarts are a genuine medical condition!

**Comment by mkurz** [comment]
@schaloner did you also publish against Scala `2.13.0-M5`?

**Comment by schaloner** [comment]
All three versions it hasn't synced with Maven Central yet, but you can see them on sonatype.

https://oss.sonatype.org/#nexus-search;gav~be.objectify~deadbolt-java_2.13.0-M5~~~~kw,versionexpand

**Comment by mkurz** [comment]
@schaloner Great, thanks!

**Comment by magro** [comment]
@schaloner can you please publish a non SNAPSHOT release for scala to maven central?

**Comment by schaloner** [comment]
@magro I've just published 2.7.0

**Pull request merged**
