### PR TITLE
WIP: Upgraded to play 2.6

### PR DESCRIPTION
**Pull request by AmazingDreams**
I upgraded to play 2.6 and fixed compile errors. All tests succeed.

I will test further. Please review this code.

### CODE REVIEW

**Comment by AmazingDreams** [comment]
#32

**Comment by schaloner** [comment]
Wow, thanks for the work!  I'll get this reviewed today and merged, and push the work I've already done on this.

**Comment by AmazingDreams** [comment]
Thanks, I just tested this in a real-world app and it all seems to work.

**Comment by schaloner** [comment]
I need to push the changes I made regarding global state in templates, add cross-version compiles, etc and it can go out by the end of the week

**Comment by schaloner** [comment]
@AmazingDreams  Would you have any time to extend the work you already did into ActionBuilders?  That would let me focus on the global state issues.

**Comment by AmazingDreams** [comment]
You mean try to fix the compile warnings? Sure I'll have a look today. I don't know your code very well so if there's anything specific you want done in a certain way let me know. 

I'll make a pull request ASAP so you can easily track the changes I made.

**Comment by etsrepo** [comment]
any update on global state in scala templates.. passing handler to templates is not a best option I feel

**Pull request merged**
